"""3474. Lexicographically Smallest Generated String
You are given two strings, str1 and str2, of lengths n and m, respectively.
A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:
If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".


Example 1:
Input: str1 = "TFTF", str2 = "ab"
Output: "ababa"
Explanation:
The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.
Return "ababa" since it is the lexicographically smaller string.


Example 2:
Input: str1 = "TFTF", str2 = "abc"
Output: ""
Explanation:
No string that satisfies the conditions can be generated.


Example 3:
Input: str1 = "F", str2 = "d"
Output: "a"
"""


class Solution:
    def generateString(self, str1: str, str2: str) -> str:
        n, m = len(str1), len(str2)
        size = n + m - 1
        
        word = ['?'] * size
        fixed = [False] * size
        
        # Step 1: Apply 'T'
        for i in range(n):
            if str1[i] == 'T':
                for j in range(m):
                    pos = i + j
                    if word[pos] == '?' or word[pos] == str2[j]:
                        word[pos] = str2[j]
                        fixed[pos] = True
                    else:
                        return ""
        
        # Step 2: Fill remaining with 'a'
        for i in range(size):
            if word[i] == '?':
                word[i] = 'a'
        
        # Step 3: Handle 'F'
        for i in range(n):
            if str1[i] == 'F':
                match = True
                for j in range(m):
                    if word[i + j] != str2[j]:
                        match = False
                        break
                
                if match:
                    changed = False
                    
                    # RIGHTMOST change (critical fix)
                    for j in range(m - 1, -1, -1):
                        pos = i + j
                        
                        if fixed[pos]:
                            continue
                        
                        original = word[pos]
                        
                        for c in 'abcdefghijklmnopqrstuvwxyz':
                            if c != original:
                                word[pos] = c
                                changed = True
                                break
                        
                        if changed:
                            break
                    
                    if not changed:
                        return ""
        
        return "".join(word)


